create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.collection_photos (
  id bigint generated by default as identity primary key,
  collection_slug text not null,
  filename text not null,
  title text,
  caption text,
  featured boolean not null default false,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (collection_slug, filename)
);

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

alter table public.admin_users enable row level security;
alter table public.collection_photos enable row level security;

drop policy if exists "Public can read collection photo metadata" on public.collection_photos;
create policy "Public can read collection photo metadata"
on public.collection_photos
for select
to anon, authenticated
using (true);

drop policy if exists "Only admin can manage metadata" on public.collection_photos;
create policy "Only admin can manage metadata"
on public.collection_photos
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin can read own admin row" on public.admin_users;
create policy "Admin can read own admin row"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

drop trigger if exists set_collection_photos_updated_at on public.collection_photos;
create trigger set_collection_photos_updated_at
before update on public.collection_photos
for each row
execute function public.set_updated_at();
